### ISSUE TITLE
For folks using a Audio Pro Device

### ISSUE THREAD

**Issue by svemat01** [Limych/media_player.linkplay#12]
Hi, me and my friend named @pnbruckner have fixed this component to work with audio pro speakers or atleast the c5. I dont really want to make a PR as the code is modified to work just with audio pro and the other ones have not been taken into consideration.
But if youre using a audio pro speaker, feel free to contact me on discord or email and i'll try to help you with it.
**Discord:** Svemat#8259
**E-mail:** Jakob.helgesson@gmail.com
Credit for it should go to pnbruckner as he was the one who told me how to do the stuff, so thanks again :)

**Comment by Limych** [comment]
Sorry, but your post does not carry any payload for this project.
